// AUTO-GENERATED BY tools/config_generator.py - DO NOT EDIT MANUALLY
#ifndef GENERATED_CONFIG_H
#define GENERATED_CONFIG_H

#include <cstdint>

namespace Config {

// System Settings
constexpr const char* DEVICE_NAME = "PopRoaster Brain";
constexpr uint8_t MODBUS_SLAVE_ID = 1;
constexpr uint32_t MODBUS_TIMEOUT_MS = 5000;

// Display Defaults
constexpr uint8_t DISPLAY_DC_PIN = 20;
constexpr uint8_t DISPLAY_RESET_PIN = 21;
constexpr uint32_t DISPLAY_UPDATE_RATE_MS = 100;
constexpr uint32_t DISPLAY_GRAPH_TIME_WINDOW_S = 60;
constexpr uint8_t DISPLAY_ROTATION = 0;

// Sensor Defaults
constexpr uint32_t SENSOR_POLL_INTERVAL_MS = 250;

// SPI Bus Definitions
constexpr size_t SPI_BUS_COUNT = 1;
struct SpiBusConfig {
    uint8_t bus_id;
    uint8_t sck_pin;
    uint8_t mosi_pin;
    uint8_t miso_pin;
};
constexpr SpiBusConfig SPI_BUSES[] = {
    {0, 18, 19, 16},
};

// Actor Definitions
constexpr size_t ACTOR_COUNT = 2;
struct ActorConfig {
    const char* id;
    const char* name;
    uint8_t pin;
    uint32_t pwm_frequency_hz;
    int8_t status_led_pin; // -1 if unused
    uint16_t modbus_holding_reg;
    uint8_t display_cs_pin;
};
constexpr ActorConfig ACTORS[] = {
    {"fan", "FAN", 15, 25000, -1, 0, 17},
    {"heater", "HEATER", 13, 2, 25, 1, 14},
};

// Sensor Definitions
constexpr size_t SENSOR_COUNT = 1;
struct SensorConfig {
    const char* id;
    const char* name;
    const char* type;
    uint8_t spi_bus;
    uint8_t cs_pin;
    uint16_t modbus_input_reg;
    uint8_t display_cs_pin;
};
constexpr SensorConfig SENSORS[] = {
    {"temp_bean", "BEAN TEMP", "MAX6675", 0, 12, 0, 11},
};

} // namespace Config

#endif // GENERATED_CONFIG_H
